services:
  sbtc:
    image: sbtc
    platform: linux/amd64
    ports:
      - "8080:8080"
    networks:
      - sbtc
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:10.6.13
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=sbtc
      - MARIADB_USER=sbtc
      - MARIADB_PASSWORD=password
    networks:
      - sbtc
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p${MARIADB_ROOT_PASSWORD}' ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

# by default, networks are named as <compose-dir>-<network name>
networks:
  sbtc: